### ISSUE TITLE
NullPointerException 해결 필요

### ISSUE THREAD

**Issue by treetrunks2** [SexyTreeTrunks/chickenProject#1]
01-18 19:14:53.366 24184-24207/? E/SQLiteDatabase: Error inserting value=1484734493377 key=sp_dot_collect_0
                                                   android.database.sqlite.SQLiteException: no such table: t_a_s_f (code 1): , while compiling: INSERT INTO t_a_s_f(value,key) VALUES (?,?)
                                                   #################################################################
                                                   Error Code : 1 (SQLITE_ERROR)
                                                   Caused By : SQL(query) error or missing database.
                                                   	(no such table: t_a_s_f (code 1): , while compiling: INSERT INTO t_a_s_f(value,key) VALUES (?,?))
                                                   #################################################################
                                                       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1000)
                                                       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:565)
                                                       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
                                                       at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                       at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1629)
                                                       at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1501)
                                                       at com.mobimagic.adv.component.AdvStatisticsProvider.insert(360Security:153)
                                                       at android.content.ContentProvider$Transport.insert(ContentProvider.java:270)
                                                       at android.content.ContentResolver.insert(ContentResolver.java:1284)
                                                       at com.mobimagic.adv.f.b.e.a(360Security:105)
                                                       at com.mobimagic.adv.d.b.e$9.onResponse(360Security:1352)
                                                       at com.android.volley.toolbox.l.deliverResponse(360Security:59)
                                                       at com.android.volley.g$a.run(360Security:103)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by treetrunks2** [comment]
각자 실행했을때 에러가 이와 같이 뜨는지 확인하여주시고 다른 에러가 발생할경우 이슈에 올려주시기 바람니다

**Comment by HeaIn** [comment]
![default](https://cloud.githubusercontent.com/assets/23717220/22089145/7c0d817a-de2c-11e6-925f-d3d0741ce721.png)

build.gradle(Module: app)에 다음 부분을 추가하고 gradle sync다시 맞춘 다음 실행시키니까 NullpointerException은 사라졌습니다. 근데 다른곳에서 에러가 나서 좀 고쳐야 할 것 같네요

![default](https://cloud.githubusercontent.com/assets/23717220/22089300/89c09234-de2d-11e6-97c9-128dd289a41b.PNG)
